import { UiLayout } from "@/components/ui/ui-layout";
import { SolanaProvider } from "@/components/solana/solana-provider";
import { ClusterProvider } from "@/components/cluster/cluster-data-access";

import { ReactQueryProvider } from "./react-query-provider";

import "./globals.css";

export const metadata = {
  title: "Reflink",
  description: "Generated by create-solana-dapp",
};

const links: { label: string; path: string }[] = [
  // { label: "Account", path: "/account" },
  // { label: "Clusters", path: "/clusters" },
  // { label: "Reflink Program", path: "/reflink" },
  { label: "Dashboard", path: "/dashboard" },
  { label: "Create Campaign", path: "/create-campaign" },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>
          <ClusterProvider>
            <SolanaProvider>
              <UiLayout links={links}>{children}</UiLayout>
            </SolanaProvider>
          </ClusterProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
